baseURL = 'https://yoshi-go.github.io/'
languageCode = 'ja-jp'
title = "Yoshi's Tech Blog"
theme = "m10c"
paginate = 10

[params.style]
  darkestColor = "#242930"
  darkColor = "#353b43"
  lightColor = "#C4CFD4"
  lightestColor = "#ffffff"
  primaryColor = "#57cc8a"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "石坂 佳大"
  description = "石坂 佳大のブログ。ベトナムのホーチミン市在住のエンジニアが技術記事、学習した事、書評、その他雑記を書いています。"
  avatar = "images/Fv-gmpoW_400x400.jpeg"
  menu_item_separator = "|"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/yoshi-go"
  [[params.social]]
    icon = "facebook"
    name = "Facebook"
    url = "https://www.facebook.com/yoshihiro.ishizaka.37"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/zack_hcmc"
  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/yoshihiro-ishizaka-b8502014b/"

[related]
  includeNewer = true
  threshold = 20
  toLower = false
  [[related.indices]]
    name = 'keywords'
    weight = 40
  [[related.indices]]
    name = 'date'
    weight = 10
  [[related.indices]]
    name = 'tags'
    weight = 50

[taxonomies]
   tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true